CREATE TABLE IF NOT EXISTS "Services" (
	"Id"	INTEGER NOT NULL,
	"Name"	TEXT NOT NULL UNIQUE,
	"LastUpdate" TEXT NOT NULL DEFAULT CURRENT_DATE,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Accounts" (
	"Id"	INTEGER NOT NULL,
	"Username"	TEXT NOT NULL,
	"Password"	TEXT NOT NULL,
	"ServiceId"	INTEGER NOT NULL DEFAULT 0,
	"LastUpdate" TEXT NOT NULL DEFAULT CURRENT_DATE,
	FOREIGN KEY("ServiceId") REFERENCES "Services"("Id") ON DELETE SET DEFAULT,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE "Config" (
	"Name"	TEXT NOT NULL UNIQUE,
	"Value"	TEXT
);
INSERT INTO "Services" ("Id","Name")
    SELECT 0,'No service' WHERE (SELECT COUNT(*) FROM "Config")=0;
INSERT INTO "Config" ("Name", "Value") 
    SELECT 'DBVersion','0.0' WHERE (SELECT COUNT(*) FROM "Config")=0;